bukkit = luajava.bindClass("org.bukkit.Bukkit")
server = bukkit:getServer()
format = luajava.bindClass("org.bukkit.ChatColor")
material = luajava.bindClass("org.bukkit.Material")
action = luajava.bindClass("org.bukkit.event.block.Action")